# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# made even `bib --help` take about four seconds. The directory form does not
# unpack anything and starts in well under a second.
class Bib < Formula
  desc "Real, unmanaged browser in a box: a Linux container or a macOS VM"
  homepage "https://github.com/sapn95/browser-in-a-box"
  version "3.3.1"
  license "MIT"

  on_macos do
    on_intel do
      # Only the container variant would work here anyway, and no Intel Mac binary
      # is published; say so instead of failing with a missing url.
      odie "bib ships macOS binaries for Apple silicon only; run ./bib.py from a checkout"
    end

    on_arm do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.3.1/bib-macos-arm64.tar.gz"
      sha256 "309121557d0fad59284d22aae540fb24ec54afdbfb81a90233b8a6b9b5be75d2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.3.1/bib-linux-arm64.tar.gz"
      sha256 "303443a5de4eebf2950b768e0692933a4c1ec6819718df81d631d33e4bd51b49"
    end
    on_intel do
      url "https://github.com/sapn95/browser-in-a-box/releases/download/v3.3.1/bib-linux-x86_64.tar.gz"
      sha256 "cd5edad5e8ba9ae55d8de27e82064b650ff25c2a699e1ce7bdc7235e0224a6e0"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"bib"
  end

  test do
    assert_match "bib #{version}", shell_output("#{bin}/bib --version")
  end
end
