# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# made even `cib --help` take about four seconds. The directory form does not
# unpack anything and starts in well under a second.
class Cib < Formula
  desc "Real Google Chrome in a box — a Linux container or a macOS VM"
  homepage "https://github.com/sapn95/chrome-in-a-box"
  version "1.4.0"
  license "MIT"

  on_macos do
    on_intel do
      # Only the container variant would work here anyway, and no Intel Mac binary
      # is published; say so instead of failing with a missing url.
      odie "cib ships macOS binaries for Apple silicon only; run ./cib.py from a checkout"
    end

    on_arm do
      url "https://github.com/sapn95/chrome-in-a-box/releases/download/v1.4.0/cib-macos-arm64.tar.gz"
      sha256 "2426f6e66e3499d8368a931266741110004956bed9b0165bb56a8483b3847433"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/chrome-in-a-box/releases/download/v1.4.0/cib-linux-arm64.tar.gz"
      sha256 "60cc61d9123436e632ffb9863bc99fe2877a574e54667e1b5d2d62c198d0301c"
    end
    on_intel do
      url "https://github.com/sapn95/chrome-in-a-box/releases/download/v1.4.0/cib-linux-x86_64.tar.gz"
      sha256 "01863de6367a8a0731816e26c27a6ee7e3f493a142ea375059ab7a35282d9307"
    end
  end

  def install
    libexec.install Dir["*"]
    bin.install_symlink libexec/"cib"
  end

  test do
    assert_match "cib #{version}", shell_output("#{bin}/cib --version")
  end
end
