# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# adds seconds to something as small as `git-tidy --help`. The directory form
# does not unpack anything and starts immediately.
class GitTidy < Formula
  desc "Keep a directory full of git checkouts clean: sync, prune, clean, sweep"
  homepage "https://github.com/sapn95/git-tidy"
  version "3.0.7"
  license "MIT"

  on_macos do
    on_intel do
      # No Intel Mac binary is published; say so instead of failing later with a
      # missing url.
      odie "git-tidy ships macOS binaries for Apple silicon only; run ./git_tidy.py from a checkout"
    end

    on_arm do
      url "https://github.com/sapn95/git-tidy/releases/download/v3.0.7/git-tidy-macos-arm64.tar.gz"
      sha256 "b67124c44ab22fcbfa68f3210e9e53c970064936f78f88ba7b6f31695edc056e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/git-tidy/releases/download/v3.0.7/git-tidy-linux-arm64.tar.gz"
      sha256 "dcb06211e5a01054e48dcd24a5da779d9d16fc1e4606313d61972e32c0f255d3"
    end
    on_intel do
      url "https://github.com/sapn95/git-tidy/releases/download/v3.0.7/git-tidy-linux-x86_64.tar.gz"
      sha256 "10fc46389852a5274169de2ab4e3c9dbd5a8ea9f59af0e6c1498a6ddfd4d4f11"
    end
  end

  def install
    # Before libexec.install, which would otherwise sweep the man page in with
    # everything else. git intercepts `git tidy --help` and looks for a man page
    # rather than passing the flag through, so one has to be where man finds it.
    man1.install "git-tidy.1" if File.exist?("git-tidy.1")
    libexec.install Dir["*"]
    bin.install_symlink libexec/"git-tidy"
  end

  test do
    assert_match "git-tidy #{version}", shell_output("#{bin}/git-tidy --version")
  end
end
