# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# adds seconds to something as small as `git-tidy --help`. The directory form
# does not unpack anything and starts immediately.
class GitTidy < Formula
  desc "Keep a directory full of git checkouts clean: sync, prune, clean, sweep"
  homepage "https://github.com/sapn95/git-tidy"
  version "3.1.1"
  license "MIT"

  on_macos do
    on_intel do
      # No Intel Mac binary is published; say so instead of failing later with a
      # missing url.
      odie "git-tidy ships macOS binaries for Apple silicon only; run ./git_tidy.py from a checkout"
    end

    on_arm do
      url "https://github.com/sapn95/git-tidy/releases/download/v3.1.1/git-tidy-macos-arm64.tar.gz"
      sha256 "b6a42dd18ccdc488ab19aa4b565da09582473f0bee23b475a6eae1de24f7706a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/git-tidy/releases/download/v3.1.1/git-tidy-linux-arm64.tar.gz"
      sha256 "a2eb927fac06f89a30208025a889bfbe79a99bbf97a2e06dc56f2d9fc8e00e85"
    end
    on_intel do
      url "https://github.com/sapn95/git-tidy/releases/download/v3.1.1/git-tidy-linux-x86_64.tar.gz"
      sha256 "7f46c4c373523c546ef7b7bb382c8ff474c7ba767784dbbec573fd0ce3c3ac9f"
    end
  end

  def install
    # Before libexec.install, which would otherwise sweep the man page in with
    # everything else. git intercepts `git tidy --help` and looks for a man page
    # rather than passing the flag through, so one has to be where man finds it.
    man1.install "git-tidy.1" if File.exist?("git-tidy.1")
    libexec.install Dir["*"]
    bin.install_symlink libexec/"git-tidy"
  end

  test do
    assert_match "git-tidy #{version}", shell_output("#{bin}/git-tidy --version")
  end
end
