# Regenerated by .github/workflows/release.yml on every tagged release, so the
# version and checksums below always match the published assets.
#
# The published asset is a Nuitka standalone build: compiled, so there is no
# interpreter and no readable source on disk. It is deliberately not a Nuitka
# *onefile* binary — onefile unpacks its whole payload on every single run, which
# adds seconds to something as small as `git-tidy --help`. The directory form
# does not unpack anything and starts immediately.
class GitTidy < Formula
  desc "Keep a directory full of git checkouts clean: sync, prune, clean, sweep"
  homepage "https://github.com/sapn95/git-tidy"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      # No Intel Mac binary is published; say so instead of failing later with a
      # missing url.
      odie "git-tidy ships macOS binaries for Apple silicon only; run ./git_tidy.py from a checkout"
    end

    on_arm do
      url "https://github.com/sapn95/git-tidy/releases/download/v1.1.0/git-tidy-macos-arm64.tar.gz"
      sha256 "d74022b42f14291fcad3cdc3881eb6d8e807b0456f62f131b9a87ed14df62a65"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sapn95/git-tidy/releases/download/v1.1.0/git-tidy-linux-arm64.tar.gz"
      sha256 "665cd246c60beda6ca10ce8c4aa9f434de2df6d0f8a50316e7548826bcb4c106"
    end
    on_intel do
      url "https://github.com/sapn95/git-tidy/releases/download/v1.1.0/git-tidy-linux-x86_64.tar.gz"
      sha256 "9e592419d5c8aeeb7d89418b9b5951cbcaa07045c980f51339df6384f9f3ef5a"
    end
  end

  def install
    # Before libexec.install, which would otherwise sweep the man page in with
    # everything else. git intercepts `git tidy --help` and looks for a man page
    # rather than passing the flag through, so one has to be where man finds it.
    man1.install "git-tidy.1" if File.exist?("git-tidy.1")
    libexec.install Dir["*"]
    bin.install_symlink libexec/"git-tidy"
  end

  test do
    assert_match "git-tidy #{version}", shell_output("#{bin}/git-tidy --version")
  end
end
